config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :features
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_in' => 'devise/sessions#new', as: :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :features

  validates_presence_of :user, :title
  after_commit :update_cache_keys, on: :update

  def update_cache_keys
    Rails.cache.write([Project, :cache_key, self.id], self.updated_at)
  end

  def self.cached_find(id)
    updated_at = Rails.cache.read([Project, :cache_key, id])
    project = nil

    if !updated_at
      project = Project.find(id)
      updated_at = project.updated_at
      project.update_cache_keys
    end

    Rails.cache.fetch([Project, :cached, id, updated_at]) do
      project ||= Project.find(id)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_breadcrumbs, only: %i[ show edit ]
  before_action :set_project, only: %i[ show edit update destroy ]


  # GET /projects or /projects.json
  def index
    authorize Project
    @projects = policy_scope(Project)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    authorize Project
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    authorize Project
    @project = Project.new(project_params.merge(user: current_user))

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_breadcrumbs
      add_breadcrumb "Projects", projects_path
    end

    def set_project
      @project = Project.cached_find(params[:id])
      authorize @project
      add_breadcrumb @project.title, project_path(@project)
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= project.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render partial: 'layouts/breadcrumbs' %>
  <hr class='my-4'/>
  <%= render "form", project: @project %>
</div>

app/views/projects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%= link_to 'New project', new_project_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="projects" class="min-w-full">
		<div class="mt-8 flow-root">
			<div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
				<div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
					<div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
						<table class="min-w-full divide-y divide-gray-300">
							<thead class="bg-gray-50">
								<tr>
									<th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
									<th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
										<span class="sr-only">Edit</span>
									</th>
								</tr>
							</thead>
							<tbody class="divide-y divide-gray-200 bg-white">
								<% @projects.each do |project| %>
									<tr>
										<td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= project.title %></td>
										<td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
											<%= link_to project, class:"text-indigo-600 hover:text-indigo-900" do %>
												View<span class="sr-only"><%= project.title %></span>
											<% end %>
										</td>
									</tr>
								<% end %>
								<!-- More people... -->
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
  
    <div id='project-toolbar' class='flex items-center gap-6 justify-between'>
      <%= render partial: 'layouts/breadcrumbs' %>
      <div class='w-min'>
        <div class="relative inline-block text-left" data-controller="drop-down-menu">
          <div>
            <button type="button" class="flex items-center rounded-full bg-gray-100 text-gray-400 hover:text-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100" id="menu-button" aria-expanded="true" aria-haspopup="true" data-action="click->drop-down-menu#toggle">
              <span class="sr-only">Open options</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M10 3a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM10 8.5a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM11.5 15.5a1.5 1.5 0 10-3 0 1.5 1.5 0 003 0z" />
              </svg>
            </button>
          </div>
          <div
              data-drop-down-menu-target='linkContainer'
              class="hidden absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
              role="menu"
              aria-orientation="vertical"
              aria-labelledby="menu-button"
              tabindex="-1"
          >
            <div class="py-1" role="none">
              <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
              <%= link_to edit_project_path(@project), class: "text-gray-700 block px-4 py-2 text-sm",role:"menuitem",tabindex:"-1" do %>
                <div class='flex items-center gap-4'>
                  <%= heroicon 'pencil' %>  Edit
                </div>
              <% end %>
              <%= link_to project_features_path(@project), class: "text-gray-700 block px-4 py-2 text-sm",role:"menuitem",tabindex:"-1" do %>
                <div class='flex items-center gap-4'>
                  <%= heroicon 'clipboard-document-list' %>  Features
                </div>
              <% end %>
              <hr class='mb-4'/>
              <%= button_to project_path(@project), method: :delete, class: "text-gray-700 block px-4 py-2 text-sm" do %>
                <div class='flex items-center gap-4'>
                  <span class='text-red-500'><%= heroicon 'trash' %></span>  Destroy
                </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>

    <hr class='my-4'/>

    <%= render @project %>

    <div>
      <div class='font-bold mb-2'>Notes:</div>
      <div id='editorjs' class='prose'></div>
    </div>
</div>