config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :features
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_in' => 'devise/sessions#new', as: :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/feature.rb
class Feature < ApplicationRecord
  enum status: {
    not_started: "not_started",
    in_progress: "in_progress",
    complete: "complete"
  }

  enum size: {
    small: "small",
    medium: "medium",
    large: "large",
  }

  belongs_to :project
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_project

  before_action :set_feature, only: %i[ show edit update destroy ]

  # GET /features or /features.json
  def index
    @features = @project.features
    add_breadcrumb "Features", "#"
  end

  # GET /features/1 or /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = @project.features.build
  end

  # GET /features/1/edit
  def edit
    add_breadcrumb "Editing", "#"
  end

  # POST /features or /features.json
  def create
    @feature = @project.features.build(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to project_feature_url(@project, @feature), notice: "Feature was successfully created." }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1 or /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to project_feature_url(@project, @feature), notice: "Feature was successfully updated." }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1 or /features/1.json
  def destroy
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url, notice: "Feature was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = @project.features.find(params[:id])
      add_breadcrumb "Features", project_features_path(@feature.project)
      add_breadcrumb @feature.title, project_feature_path(@feature.project, @feature)
    end

    # Only allow a list of trusted parameters through.
    def feature_params
      params.require(:feature).permit(:status, :title, :size)
    end

    def set_project
      @project ||= Project.cached_find(params[:project_id])
      authorize @project
      add_breadcrumb @project.title, project_path(@project)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
  def status_color(feature)
    if feature.in_progress?
      "bg-orange-200 text-orange-600"
    elsif feature.not_started?
      "bg-gray-200 text-gray-600" 
    elsif feature.complete?
      "bg-green-300 text-green-700" 
    else
      "text-gray-800"
    end
  end
end

app/views/features/_feature.html.erb
<li>
  <a href="<%= project_feature_path(feature.project, feature) %>" class="block hover:bg-gray-50">
    <div class="px-4 py-4 sm:px-6">
      <div class="flex items-center justify-between">
        <p class="truncate text-sm font-medium text-emerald-800"><%= feature.title %></p>
        <div class="ml-2 flex flex-shrink-0">
          <p class="inline-flex rounded-full <%= status_color(feature) %> px-2 text-xs font-semibold leading-5"><%= feature.status&.titleize %></p>
        </div>
      </div>
      <div class="mt-2 sm:flex sm:justify-between">
        <div class="sm:flex">
          <p class="flex items-center text-sm text-gray-500">
          <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 295.526 295.526" fill="currentColor" aria-hidden="true">
            <g>
              <path d="M147.763,44.074c12.801,0,23.858-8.162,27.83-20.169c-7.578,2.086-17.237,3.345-27.83,3.345
                c-10.592,0-20.251-1.259-27.828-3.345C123.905,35.911,134.961,44.074,147.763,44.074z"/>
              <path d="M295.158,58.839c-0.608-1.706-1.873-3.109-3.521-3.873l-56.343-26.01c-11.985-4.06-24.195-7.267-36.524-9.611
                c-0.434-0.085-0.866-0.126-1.292-0.126c-3.052,0-5.785,2.107-6.465,5.197c-4.502,19.82-22.047,34.659-43.251,34.659
                c-21.203,0-38.749-14.838-43.25-34.659c-0.688-3.09-3.416-5.197-6.466-5.197c-0.426,0-0.858,0.041-1.292,0.126
                c-12.328,2.344-24.538,5.551-36.542,9.611L3.889,54.965c-1.658,0.764-2.932,2.167-3.511,3.873
                c-0.599,1.726-0.491,3.589,0.353,5.217l24.46,48.272c1.145,2.291,3.474,3.666,5.938,3.666c0.636,0,1.281-0.092,1.917-0.283
                l27.167-8.052v161.97c0,3.678,3.001,6.678,6.689,6.678h161.723c3.678,0,6.67-3.001,6.67-6.678V107.66l27.186,8.052
                c0.636,0.191,1.28,0.283,1.915,0.283c2.459,0,4.779-1.375,5.94-3.666l24.469-48.272C295.629,62.428,295.747,60.565,295.158,58.839z
                "/>
            </g>
            </svg>
            Size: <%= feature.size&.titleize %>
          </p>
          <p class="mt-2 flex items-center text-sm text-gray-500 sm:ml-6 sm:mt-0">
            <%= heroicon 'arrow-long-up', options: { class: 'mr-1.5 flex-shrink-0 text-gray-400 w-5' } %>
            Priority: Low
          </p>
        </div>
        <div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
          <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M5.75 2a.75.75 0 01.75.75V4h7V2.75a.75.75 0 011.5 0V4h.25A2.75 2.75 0 0118 6.75v8.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25v-8.5A2.75 2.75 0 014.75 4H5V2.75A.75.75 0 015.75 2zm-1 5.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h10.5c.69 0 1.25-.56 1.25-1.25v-6.5c0-.69-.56-1.25-1.25-1.25H4.75z" clip-rule="evenodd" />
          </svg>
          <p>
            Hope to deliver by:
            <time datetime="2020-01-07">January 7, 2020</time>
          </p>
        </div>
      </div>
    </div>
  </a>
</li>

app/views/features/_form.html.erb
<%= form_with(model: [@project, feature], class: "contents w-full") do |form| %>
  <% if feature.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
        <% feature.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <div>
      <%= form.label :status %>
    </div>
    <%= form.select :status, options_for_select(Feature.statuses.map {|key, value| [key.titleize, Feature.statuses.key(value)]}, feature.status),{}, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"} %>
  </div>


  <div class='flex justify-between gap-4 my-5'>
    <%= form.label :size_small, class: 'w-1/3 flex flex-col items-center border border-solid border-gray-200 border-rounded p-2 rounded shadow' do %>
      S
      <%= form.radio_button :size, :small %>
    <% end %>
    <%= form.label :size_medium, class: 'w-1/3 flex flex-col items-center border border-solid border-gray-200 border-rounded p-2 rounded shadow' do %>
      M
      <%= form.radio_button :size, :medium %>
    <% end %>
    <%= form.label :size_large, class: 'w-1/3 flex flex-col items-center border border-solid border-gray-200 border-rounded p-2 rounded shadow' do %>
      L
      <%= form.radio_button :size, :large %>
    <% end %>
  </div>

  <div class='flex justify-between gap-4 my-5 w-full my-5'>
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer w-full" %>
  </div>
<% end %>

app/views/features/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render partial: 'layouts/breadcrumbs' %>
  <hr class='my-4'/>

  <%= render "form", feature: @feature %>
</div>

app/views/features/index.html.erb
<div class='w-full'>
  <div id='features-toolbar' class='flex items-center gap-6 justify-between'>
    <%= render partial: 'layouts/breadcrumbs' %>
    <div class='w-min'>
      <div class="relative inline-block text-left" data-controller="drop-down-menu">
        <div>
          <button type="button" class="flex items-center rounded-full bg-gray-100 text-gray-400 hover:text-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100" id="menu-button" aria-expanded="true" aria-haspopup="true" data-action="click->drop-down-menu#toggle">
            <span class="sr-only">Open options</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M10 3a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM10 8.5a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM11.5 15.5a1.5 1.5 0 10-3 0 1.5 1.5 0 003 0z" />
            </svg>
          </button>
        </div>
        <div
            data-drop-down-menu-target='linkContainer'
            class="hidden absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
            role="menu"
            aria-orientation="vertical"
            aria-labelledby="menu-button"
            tabindex="-1"
        >
          <div class="py-1" role="none">
            <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
            <%= link_to new_project_feature_path(@project), class: "text-gray-700 block px-4 py-2 text-sm",role:"menuitem",tabindex:"-1" do %>
              <div class='flex items-center gap-4'>
                <%= heroicon 'plus' %>  Add Feature
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <div id="features" class="min-w-full">
      <ul role="list" class="divide-y divide-gray-200">
        <%= render @features %>
      </ul>
    </div>
  </div>
</div>

app/views/features/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New feature</h1>

  <%= render "form", feature: @feature %>

  <%= link_to 'Back to features', project_features_path(@project), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/features/show.html.erb
<div class='w-full'>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div id='features-toolbar' class='flex items-center gap-6 justify-between'>
    <%= render partial: 'layouts/breadcrumbs' %>
  </div>
  <hr class='my-4'/>
  <ul>
    <%= render @feature %>
  </ul>
  <div class='grid grid-cols-1 gap-4'>
    <%= link_to 'Edit', edit_project_feature_path(@project, @feature), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 text-gray-500 inline-block font-medium block" %>
    <%= button_to 'Destroy', project_feature_path(@project, @feature), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-300 font-bold text-red-700 w-full text-left" %>
  </div>
</div>